// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh23gr9fEB6BZyHRpvrpchS0rGz3ykjao',
    appId: '1:5276167370:web:a6a203f22cd3e151c51833',
    messagingSenderId: '5276167370',
    projectId: 'agoravideocall-6b8e9',
    authDomain: 'agoravideocall-6b8e9.firebaseapp.com',
    storageBucket: 'agoravideocall-6b8e9.firebasestorage.app',
    measurementId: 'G-Y23132JSVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8k5X2o94GIZAS0nKKpRwecktDR2hJSSw',
    appId: '1:5276167370:android:922c323e84274d51c51833',
    messagingSenderId: '5276167370',
    projectId: 'agoravideocall-6b8e9',
    storageBucket: 'agoravideocall-6b8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbZ-MvvgBl2eaTjjn2kt8Ulwict9_60A',
    appId: '1:5276167370:ios:0324c36c460c795bc51833',
    messagingSenderId: '5276167370',
    projectId: 'agoravideocall-6b8e9',
    storageBucket: 'agoravideocall-6b8e9.firebasestorage.app',
    iosBundleId: 'com.syedbipul.mastercaller.masterCaller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbZ-MvvgBl2eaTjjn2kt8Ulwict9_60A',
    appId: '1:5276167370:ios:0324c36c460c795bc51833',
    messagingSenderId: '5276167370',
    projectId: 'agoravideocall-6b8e9',
    storageBucket: 'agoravideocall-6b8e9.firebasestorage.app',
    iosBundleId: 'com.syedbipul.mastercaller.masterCaller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh23gr9fEB6BZyHRpvrpchS0rGz3ykjao',
    appId: '1:5276167370:web:ab71cb3572c970e6c51833',
    messagingSenderId: '5276167370',
    projectId: 'agoravideocall-6b8e9',
    authDomain: 'agoravideocall-6b8e9.firebaseapp.com',
    storageBucket: 'agoravideocall-6b8e9.firebasestorage.app',
    measurementId: 'G-PY1TFDN7B2',
  );
}
